//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alex.authorization {
	
	
	public partial class Login {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlInputText email;
		
		protected System.Web.UI.HtmlControls.HtmlInputText password;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor login;
	}
}
