//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alex.admin {
	
	
	public partial class AddGood {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlInputText name;
		
		protected System.Web.UI.HtmlControls.HtmlTextArea description;
		
		protected System.Web.UI.HtmlControls.HtmlSelect type;
		
		protected System.Web.UI.HtmlControls.HtmlInputText price;
		
		protected System.Web.UI.HtmlControls.HtmlInputFile file;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor add;
	}
}
