//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alex.admin {
	
	
	public partial class Admin {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor s;
		
		protected System.Web.UI.HtmlControls.HtmlInputControl id;
		
		protected System.Web.UI.HtmlControls.HtmlInputControl name;
		
		protected System.Web.UI.HtmlControls.HtmlInputControl description;
		
		protected System.Web.UI.HtmlControls.HtmlInputControl price;
	}
}
